cocos2dSDK: DroiTaskDispatcher Class Reference
DroiTaskDispatcher Class Reference
Public Member Functions
DROITASKID enqueueTask (const DROITASK &task)
DROITASKID enqueueTask (const DROITASK &task, int delayInMillisecond)
DROITASKID enqueueTask (const std::string &taskName, const DROITASK &task)
DROITASKID enqueueTask (const std::string &taskName, const DROITASK &task, int delayInMillisecond)
DROITASKID enqueueTimerTask (const DROITASK &task, int intervalInMillisecond, bool runOnce)
DROITASKID enqueueTimerTask (const std::string &taskName, const DROITASK &task, int intervalInMillisecond, bool runOnce)
bool killTask (DROITASKID taskId)
void destroy ()
Static Public Member Functions
static DroiTaskDispatcher & getTaskDispatcher (const std::string &dispatcherName)
static DroiTaskDispatcher * currentTaskDispatcher ()
static DROITASKID taskIdByName (const std::string &taskName)
Member Function Documentation
currentTaskDispatcher()
DroiTaskDispatcher * DroiTaskDispatcher::currentTaskDispatcher () static
Get DroiTaskDispatcher object of current thread
Returns
DroiTaskDispatcher instance
References getTaskDispatcher().
Referenced by DroiQuery::offset(), DroiUser::refreshValidationStatus(), DroiUser::refreshValidationStatusInBackground(), DroiQuery::runInBackground(), DroiQuery::runQueryInBackground(), and DroiObject::saveInBackground().
destroy()
void DroiTaskDispatcher::destroy ()
Destroy DroiTaskDispatcher object
enqueueTask() [1/4]
DROITASKID DroiTaskDispatcher::enqueueTask (const DROITASK & task)
Enqueue a task into DroiTaskDispatcher
Parameters
task The task that will be executed
Returns
The id of enqueued task
Referenced by enqueueTask(), DroiQuery::offset(), DroiUser::refreshValidationStatus(), DroiUser::refreshValidationStatusInBackground(), DroiQuery::runInBackground(), DroiQuery::runQueryInBackground(), and DroiObject::saveInBackground().
enqueueTask() [2/4]
DROITASKID DroiTaskDispatcher::enqueueTask (const DROITASK & task, int delayInMillisecond)
Enqueue a task into DroiTaskDispatcher
Parameters
task The task that will be executed
delayInMillisecond Delay in millisecond
Returns
The id of enqueued task
References enqueueTask().
enqueueTask() [3/4]
DROITASKID DroiTaskDispatcher::enqueueTask (const std::string & taskName, const DROITASK & task)
Enqueue a task into DroiTaskDispatcher
Parameters
taskName The specific task name
task The task that will be executed
Returns
The id of enqueued task
References enqueueTask().
enqueueTask() [4/4]
DROITASKID DroiTaskDispatcher::enqueueTask (const std::string & taskName, const DROITASK & task, int delayInMillisecond)
Enqueue a task into DroiTaskDispatcher
Parameters
taskName The specific task name
task The task that will be executed
delayInMillisecond Delay in millisecond
Returns
The id of enqueued task
References enqueueTimerTask().
enqueueTimerTask() [1/2]
DROITASKID DroiTaskDispatcher::enqueueTimerTask (const DROITASK & task, int intervalInMillisecond, bool runOnce)
Enqueue a timer task into DroiTaskDispatcher
Parameters
task The task that will be executed
intervalInMillisecond The interval in millisecond
runOnce Check whether this task is running once
Returns
The id of enqueued task
Referenced by enqueueTask().
enqueueTimerTask() [2/2]
DROITASKID DroiTaskDispatcher::enqueueTimerTask (const std::string & taskName, const DROITASK & task, int intervalInMillisecond, bool runOnce)
Enqueue a timer task into DroiTaskDispatcher
Parameters
taskName The specific task name
task The task that will be executed
intervalInMillisecond The interval in millisecond
runOnce Check whether this task is running once
Returns
The id of enqueued task
getTaskDispatcher()
DroiTaskDispatcher & DroiTaskDispatcher::getTaskDispatcher (const std::string & dispatcherName) static
Get the specific DroiTaskDispatcher object by dispatcherName
Parameters
dispatcherName The dispatcher name
Returns
DroiTaskDispatcher instance
Referenced by currentTaskDispatcher(), DroiQuery::offset(), DroiUser::refreshValidationStatus(), DroiUser::refreshValidationStatusInBackground(), DroiQuery::runInBackground(), DroiQuery::runQueryInBackground(), and DroiObject::saveInBackground().
killTask()
bool DroiTaskDispatcher::killTask (DROITASKID taskId)
Kill the specific task
Parameters
taskId The specific task id
Returns
true - succeeded; Otherwise is false
taskIdByName()
DROITASKID DroiTaskDispatcher::taskIdByName (const std::string & taskName) static
Get task id by name
Parameters
taskName the name of task
Returns
The id of task by taskName
The documentation for this class was generated from the following files:
DroiTaskDispatcher.h
DroiTaskDispatcher.cpp