cocos2dSDK: DroiUser Class Reference
DroiUser Class Reference
Public Member Functions
DroiError logout ()
DroiError signup ()
bool isAnonymouseUser ()
bool isLoggedIn ()
bool enabled ()
void setEnabled (bool enabled)
std::string getUserId ()
std::string getEmail ()
std::string getPhoneNumber ()
std::string getSessionToken ()
void setUserId (const std::string &userId)
void setPassword (const std::string &password)
void setEmail (const std::string &email)
void setPhoneNumber (const std::string &phoneNumber)
DroiError changePassword (const std::string &oldPassword, const std::string newPassword)
DroiError validateEmail ()
DroiError validatePhoneNumber ()
DroiError confirmPhoneNumberPinCode (const std::string &pinCode)
bool refreshValidationStatus ()
bool refreshValidationStatusInBackground (DroiCallback< RefPtr< DroiUser >>::onCallback2 callback)
bool isEmailVerified ()
bool isPhoneNumVerified ()
Public Member Functions inherited from DroiObject
std::string getClassName () const
void setValue (const std::string &keyName, bool value)
void setValue (const std::string &keyName, int32_t value)
void setValue (const std::string &keyName, const std::string &value)
void setValue (const std::string &keyName, double value)
void setValue (const string &keyName, const cocos2d::Value &value)
void setValue (const string &keyName, const cocos2d::ValueVector &value)
void setValue (const string &keyName, const cocos2d::ValueMap &value)
void setValue (const string &keyName, const RefVector &value)
void setValue (const string &keyName, const RefMap &value)
void setValue (const string &keyName, DroiObject *value)
void setValue (const string &keyName, DroiDateTime value)
void eraseValue (const string &keyName)
bool hasValue (const std::string &keyName)
bool getValue (const string &keyName, bool &value)
bool getValue (const std::string &keyName, int32_t &value)
bool getValue (const std::string &keyName, std::string &value)
bool getValue (const std::string &keyName, double &value)
bool getValue (const string &keyName, cocos2d::Value &value)
bool getValue (const string &keyName, cocos2d::ValueVector &value)
bool getValue (const string &keyName, cocos2d::ValueMap &value)
bool getValue (const string &keyName, RefVector &value)
bool getValue (const string &keyName, RefMap &value)
bool getValue (const string &keyName, DroiObject *&value)
bool getValue (const string &keyName, DroiDateTime &value)
bool isDirty ()
std::string objectId () const
DroiPermission * getPermissionWithDefault () const
void setPermission (DroiPermission *permission)
DroiPermission * getPermission ()
DroiObject * clone ()
virtual DroiError save ()
virtual DroiError deleteFromStoage ()
void saveInBackground (DroiCallback< DroiError >::onCallback callback)
bool toJson (std::string &result)
Static Public Member Functions
static DroiUser * create ()
static DroiUser * getCurrentUser ()
static RefPtr< DroiUser > login (const std::string &userId, const std::string &password, DroiError *error)
static RefPtr< DroiUser > loginWithAnonymous (DroiError *error)
static void setAutoAnonymouseUser (bool flag)
static bool isAutoAnonymousUserEnabled ()
Static Public Member Functions inherited from DroiObject
static void registerCustomClass (std::string classname, createObject factory)
static DroiObject * createObject (std::string className)
static DroiObject * fromJSON (const std::string &jsonString)
static DroiError saveAll (RefVector *items)
Friends
class cJSONHelper
class CloudStorageDBHelper
class CloudUserStorageDBHelper
Additional Inherited Members
Protected Member Functions inherited from DroiObject
DroiObject (const std::string &className)
void set (const std::string &keyName, Ref *refValue)
Ref * get (const std::string &keyName)
void copyFrom (const DroiObject *obj)
Member Function Documentation
changePassword()
DroiError DroiUser::changePassword (const std::string & oldPassword, const std::string newPassword)
Reset user password
Parameters
oldPassword Old password to be check again
newPassword New password to be set
Returns
DroiError DroiError object. Developer should use isOk to check whether this result is OK.
confirmPhoneNumberPinCode()
DroiError DroiUser::confirmPhoneNumberPinCode (const std::string & pinCode)
Confirm pin code sent to user phone.
Parameters
pinCode Pic code
Returns
DroiError DroiError object. Developer should use isOk to check whether this result is OK.
create()
DroiUser * DroiUser::create () static
Constructor a DroiUser object.
Returns
DroiUser instance
enabled()
bool DroiUser::enabled ()
Get isEnabled state.
Returns
true if it's enabled.
getCurrentUser()
DroiUser * DroiUser::getCurrentUser () static
Get cuurent login user.
Returns
DroiUser instance
Referenced by login(), loginWithAnonymous(), and signup().
getEmail()
std::string DroiUser::getEmail ()
Get user email.
Returns
User email.
getPhoneNumber()
std::string DroiUser::getPhoneNumber ()
Get user phone number.
Returns
User phone number.
getSessionToken()
std::string DroiUser::getSessionToken ()
Get user phone number.
Returns
User phone number.
getUserId()
std::string DroiUser::getUserId ()
Get user id.
Returns
User id.
isAnonymouseUser()
bool DroiUser::isAnonymouseUser ()
The user is anonymous.
Returns
true for anonlymous user.
Referenced by signup().
isAutoAnonymousUserEnabled()
bool DroiUser::isAutoAnonymousUserEnabled () static
Get AutoAnonymousUserEnable state.
Returns
true to enable.
isEmailVerified()
bool DroiUser::isEmailVerified ()
Email field has been verified or not.
Returns
true to EmailVerified is true or false otherwise.
isLoggedIn()
bool DroiUser::isLoggedIn ()
The user login state.
Returns
true to login successfully and not expired.
References DroiDateTime::isValidISO8601String().
Referenced by signup().
isPhoneNumVerified()
bool DroiUser::isPhoneNumVerified ()
PhonNum field has been verified or not.
Returns
true to PhoneNumVerified is true or false otherwise.
login()
RefPtr< DroiUser > DroiUser::login (const std::string & userId, const std::string & password, DroiError * error) static
Login user with UserID and Password
Parameters
userId UserId
password Password
error Pass DroiError to get error code. Pass null to ignore error details.
Returns
DroiUser instance.
References getCurrentUser(), and DroiCore::getInstallationId().
loginWithAnonymous()
RefPtr< DroiUser > DroiUser::loginWithAnonymous (DroiError * error) static
Login user with anonymous type.
Parameters
error Pass DroiError to get error code. Pass null to ignore error details.
References getCurrentUser(), DroiPermission::getDefaultPermission(), DroiCore::getDeviceId(), DroiCore::getInstallationId(), DroiObject::setPermission(), DroiPermission::setPublicReadPermission(), and DroiPermission::setPublicWritePermission().
logout()
DroiError DroiUser::logout ()
Logout current user. The logout is block action and need network connected.
Returns
DroiError object.
refreshValidationStatus()
bool DroiUser::refreshValidationStatus ()
Refersh EmailVerified / PhoneNumVerified field status. After refreshed, check verification via isEmailVerified or isPhoneNumVerified.
Returns
true to successfully refreshed.
References DroiTaskDispatcher::currentTaskDispatcher(), DroiTaskDispatcher::enqueueTask(), DroiTaskDispatcher::getTaskDispatcher(), DroiObject::getValue(), DroiQuery::queryData(), DroiQuery::runQuery(), and DroiQuery::where().
refreshValidationStatusInBackground()
bool DroiUser::refreshValidationStatusInBackground (DroiCallback< RefPtr< DroiUser >>::onCallback2 callback)
Refersh EmailVerified / PhoneNumVerified field status in the background thread. After refreshed, check verification via isEmailVerified or isPhoneNumVerified.
Parameters
callback Callback
Returns
true to successfully push to background task to execute.
References DroiTaskDispatcher::currentTaskDispatcher(), DroiTaskDispatcher::enqueueTask(), and DroiTaskDispatcher::getTaskDispatcher().
setAutoAnonymouseUser()
void DroiUser::setAutoAnonymouseUser (bool flag) static
To save data to cloud, the action must send with valid login user. Will auto login with anonymous user if not login before when saving data.
Parameters
flag true to enable.
setEmail()
void DroiUser::setEmail (const std::string & email)
Set user email.
Parameters
email User email.
setEnabled()
void DroiUser::setEnabled (bool enabled)
Set enable state
Parameters
flag true to enable.
setPassword()
void DroiUser::setPassword (const std::string & password)
Set user password. The password is for user signup.
Parameters
password User password.
setPhoneNumber()
void DroiUser::setPhoneNumber (const std::string & phoneNumber)
Set user phone number.
Parameters
phoneNum User phone number.
setUserId()
void DroiUser::setUserId (const std::string & userId)
Set user id. The id is for user signup.
Parameters
userId User id
signup()
DroiError DroiUser::signup ()
Signup new user. The setUserId(String) and setPassword(String) must set before calling signup.
Returns
DroiError object.
References getCurrentUser(), DroiCore::getDeviceId(), DroiCore::getInstallationId(), isAnonymouseUser(), isLoggedIn(), and DroiObject::setValue().
validateEmail()
DroiError DroiUser::validateEmail ()
Validate user email.
Returns
DroiError DroiError object. Developer should use isOk to check whether this result is OK.
validatePhoneNumber()
DroiError DroiUser::validatePhoneNumber ()
Validate user phone number.
Returns
DroiError DroiError object. Developer should use isOk to check whether this result is OK.
The documentation for this class was generated from the following files:
DroiUser.h
DroiUser.cpp