cocos2dSDK: DroiQuery Class Reference
DroiQuery Class Reference
#include <DroiQuery.h>
Public Member Functions
DroiError run ()
void runInBackground (DroiCallback< DroiError >::onCallback callback)
RefVector * runQuery (DroiError *error)
void runQueryInBackground (DroiCallback< RefVector *>::onCallback2 callback)
DroiQuery & queryData (const std::string &tableName)
DroiQuery & deleteData (const std::string &tableName, DroiObject &obj)
DroiQuery & updateData (const std::string &tableName)
DroiQuery & updateObject (const std::string &tableName, DroiObject &obj)
DroiQuery & countData (const std::string &tableName)
DroiQuery & inc (const std::string &propertyName)
DroiQuery & dec (const std::string &propertyName)
DroiQuery & set (const std::string &propertyName, const cocos2d::Value &value)
DroiQuery & where (const std::string &propertyName, const std::string &opType, const cocos2d::Value &arg2)
DroiQuery & where (DroiCondition *cond)
DroiQuery & orderBy (const std::string &propertyName, bool ascending)
DroiQuery & limit (int limitSize)
DroiQuery & offset (int position)
Static Public Member Functions
static DroiQuery * create ()
Static Public Attributes
static std::string SELECT = "select"
static std::string INSERT = "insert"
static std::string DELETE = "delete"
static std::string UPDATE = "update"
static std::string COUNT = "count"
static std::string UPDATE_DATA = "updateData"
static std::string WHERE = "where"
static std::string COND = "cond"
static std::string VALUES = "values"
static std::string OR = "or"
static std::string AND = "and"
static std::string INC = "inc"
static std::string DEC = "dec"
static std::string SET = "set"
static std::string ORDERBY = "orderby"
static std::string ASC = "ASC"
static std::string DESC = "DESC"
static std::string LIMIT = "limit"
static std::string OFFSET = "offset"
Detailed Description
The DroiQuery class defines a query that is used to query DroiObject.
Member Function Documentation
countData()
DroiQuery & DroiQuery::countData (const std::string & tableName)
Count query data from specific table
Parameters
tableName Specify table name
Returns
DroiQuery instance
dec()
DroiQuery & DroiQuery::dec (const std::string & propertyName)
Decrease data by specific key
Parameters
propertyName The specific key
Returns
DroiQuery instance
deleteData()
DroiQuery & DroiQuery::deleteData (const std::string & tableName, DroiObject & obj)
Delete data from specific table
Parameters
tableName Specify table name
Returns
DroiQuery instance
Referenced by DroiObject::deleteFromStoage().
inc()
DroiQuery & DroiQuery::inc (const std::string & propertyName)
Increase data by specific key
Parameters
propertyName The specific key
Returns
DroiQuery instance
limit()
DroiQuery & DroiQuery::limit (int limitSize)
Set the maximum number of query result
Parameters
limitSize The maximum number of query result. Default number is 200
Returns
DroiQuery instance
offset()
DroiQuery & DroiQuery::offset (int position)
The query result starting at specific offset
Parameters
position The specific offset
Returns
DroiQuery instance
References DroiTaskDispatcher::currentTaskDispatcher(), DroiTaskDispatcher::enqueueTask(), and DroiTaskDispatcher::getTaskDispatcher().
orderBy()
DroiQuery & DroiQuery::orderBy (const std::string & propertyName, bool ascending)
Sort the query result by given value
Parameters
propertyName The key name to sort
ascending Determine whether the ascending sort
Returns
DroiQuery instance
queryData()
DroiQuery & DroiQuery::queryData (const std::string & tableName)
Query data from specific table
Parameters
tableName Specify table name
Returns
DroiQuery instance
Referenced by DroiUser::refreshValidationStatus().
run()
DroiError DroiQuery::run ()
Run DroiQuery instruction
Returns
DroiError object.
References runQuery().
Referenced by runInBackground().
runInBackground()
void DroiQuery::runInBackground (DroiCallback< DroiError >::onCallback callback)
Run DroiQuery instruction in background thread
Parameters
callback DroiQuery would execute callback method after finishing
References DroiTaskDispatcher::currentTaskDispatcher(), DroiTaskDispatcher::enqueueTask(), DroiTaskDispatcher::getTaskDispatcher(), and run().
runQuery()
RefVector * DroiQuery::runQuery (DroiError * error)
Run DroiQuery to query data
Parameters
error A pointer to DroiError object. You may specify nullptr for this parameter if you do not want the error information.
Returns
Query results.
Referenced by DroiObject::deleteFromStoage(), DroiUser::refreshValidationStatus(), run(), runQueryInBackground(), and DroiObject::save().
runQueryInBackground()
void DroiQuery::runQueryInBackground (DroiCallback< RefVector *>::onCallback2 callback)
Run DroiQuery to query data in background thread
Parameters
callback DroiQuery would execute callback method after finishing
References DroiTaskDispatcher::currentTaskDispatcher(), DroiTaskDispatcher::enqueueTask(), DroiTaskDispatcher::getTaskDispatcher(), and runQuery().
set()
DroiQuery & DroiQuery::set (const std::string & propertyName, const cocos2d::Value & value)
Set specific key data to value
Parameters
propertyName The specific key
value The update data
Returns
DroiQuery instance
updateData()
DroiQuery & DroiQuery::updateData (const std::string & tableName)
Update data from specific table
Parameters
tableName Specify table name
Returns
DroiQuery instance
where() [1/2]
DroiQuery & DroiQuery::where (const std::string & propertyName, const std::string & opType, const cocos2d::Value & arg2)
Add condition for query
Parameters
propertyName The key of condition to check
opType The condition type.
arg2 The value is for checking
Returns
DroiQuery instance
Referenced by DroiUser::refreshValidationStatus().
where() [2/2]
DroiQuery & DroiQuery::where (DroiCondition * cond)
Add condition for query
Parameters
cond A DroiCondtion.
Returns
DroiQuery instance
The documentation for this class was generated from the following files:
DroiQuery.h
DroiQuery.cpp