cocos2dSDK: DroiObject Class Reference
DroiObject Class Reference
#include <DroiObject.h>
Public Member Functions
std::string getClassName () const
void setValue (const std::string &keyName, bool value)
void setValue (const std::string &keyName, int32_t value)
void setValue (const std::string &keyName, const std::string &value)
void setValue (const std::string &keyName, double value)
void setValue (const string &keyName, const cocos2d::Value &value)
void setValue (const string &keyName, const cocos2d::ValueVector &value)
void setValue (const string &keyName, const cocos2d::ValueMap &value)
void setValue (const string &keyName, const RefVector &value)
void setValue (const string &keyName, const RefMap &value)
void setValue (const string &keyName, DroiObject *value)
void setValue (const string &keyName, DroiDateTime value)
void eraseValue (const string &keyName)
bool hasValue (const std::string &keyName)
bool getValue (const string &keyName, bool &value)
bool getValue (const std::string &keyName, int32_t &value)
bool getValue (const std::string &keyName, std::string &value)
bool getValue (const std::string &keyName, double &value)
bool getValue (const string &keyName, cocos2d::Value &value)
bool getValue (const string &keyName, cocos2d::ValueVector &value)
bool getValue (const string &keyName, cocos2d::ValueMap &value)
bool getValue (const string &keyName, RefVector &value)
bool getValue (const string &keyName, RefMap &value)
bool getValue (const string &keyName, DroiObject *&value)
bool getValue (const string &keyName, DroiDateTime &value)
bool isDirty ()
std::string objectId () const
DroiPermission * getPermissionWithDefault () const
void setPermission (DroiPermission *permission)
DroiPermission * getPermission ()
DroiObject * clone ()
virtual DroiError save ()
virtual DroiError deleteFromStoage ()
void saveInBackground (DroiCallback< DroiError >::onCallback callback)
bool toJson (std::string &result)
Static Public Member Functions
static void registerCustomClass (std::string classname, createObject factory)
static DroiObject * createObject (std::string className)
static DroiObject * fromJSON (const std::string &jsonString)
static DroiError saveAll (RefVector *items)
Protected Member Functions
DroiObject (const std::string &className)
void set (const std::string &keyName, Ref *refValue)
Ref * get (const std::string &keyName)
void copyFrom (const DroiObject *obj)
Friends
class cJSONHelper
Detailed Description
The DroiObject is the basic data type that can be saved and retrieved from the droi cloud service.
Member Function Documentation
clone()
DroiObject * DroiObject::clone ()
Clone current object
Returns
The clone object
References createObject().
createObject()
DroiObject * DroiObject::createObject (std::string className) static
Create DroiObject object with className
Parameters
className The class name of created object.
Returns
DroiObject instance
Referenced by clone().
deleteFromStoage()
DroiError DroiObject::deleteFromStoage () virtual
Delete current object from cloud storage
Returns
DroiErr that indicate the error code
References DroiQuery::deleteData(), and DroiQuery::runQuery().
eraseValue()
void DroiObject::eraseValue (const string & keyName)
Remove a value by key from DroiObject
Parameters
keyName The key name
fromJSON()
DroiObject * DroiObject::fromJSON (const std::string & jsonString) static
Create DroiObject from specific json string
Parameters
jsonString The json string of DroiObject
Returns
The DroiObject instance by json string
getClassName()
std::string DroiObject::getClassName () const inline
Get class name of object
Returns
The class name of object.
getPermissionWithDefault()
DroiPermission * DroiObject::getPermissionWithDefault () const
Get default permission object
Returns
The default permission object
References DroiPermission::getDefaultPermission().
getValue() [1/11]
bool DroiObject::getValue (const string & keyName, bool & value)
Get value by specific keyName
Parameters
keyName The key name
value The reference value of boolean
Returns
true Get value succeeded; Otherwise is false
Referenced by DroiUser::refreshValidationStatus(), and setValue().
getValue() [2/11]
bool DroiObject::getValue (const std::string & keyName, int32_t & value)
Get value by specific keyName
Parameters
keyName The key name
value The reference value of integer
Returns
true Get value succeeded; Otherwise is false
getValue() [3/11]
bool DroiObject::getValue (const std::string & keyName, std::string & value)
Get value by specific keyName
Parameters
keyName The key name
value The reference value of std::string
Returns
true Get value succeeded; Otherwise is false
getValue() [4/11]
bool DroiObject::getValue (const std::string & keyName, double & value)
Get value by specific keyName
Parameters
keyName The key name
value The reference value of double
Returns
true Get value succeeded; Otherwise is false
getValue() [5/11]
bool DroiObject::getValue (const string & keyName, cocos2d::Value & value)
Get value by specific keyName
Parameters
keyName The key name
value The reference value of cocos2d::Value
Returns
true Get value succeeded; Otherwise is false
getValue() [6/11]
bool DroiObject::getValue (const string & keyName, cocos2d::ValueVector & value)
Get value by specific keyName
Parameters
keyName The key name
value The reference value of cocos2d::ValueVector
Returns
true Get value succeeded; Otherwise is false
getValue() [7/11]
bool DroiObject::getValue (const string & keyName, cocos2d::ValueMap & value)
Get value by specific keyName
Parameters
keyName The key name
value The reference value of cocos2d::ValueMap
Returns
true Get value succeeded; Otherwise is false
getValue() [8/11]
bool DroiObject::getValue (const string & keyName, RefVector & value)
Get value by specific keyName
Parameters
keyName The key name
value The reference value of RefVector
Returns
true Get value succeeded; Otherwise is false
getValue() [9/11]
bool DroiObject::getValue (const string & keyName, RefMap & value)
Get value by specific keyName
Parameters
keyName The key name
value The reference value of RefMap
Returns
true Get value succeeded; Otherwise is false
getValue() [10/11]
bool DroiObject::getValue (const string & keyName, DroiObject *& value)
Get value by specific keyName
Parameters
keyName The key name
value The reference value of DroiObject
Returns
true Get value succeeded; Otherwise is false
getValue() [11/11]
bool DroiObject::getValue (const string & keyName, DroiDateTime & value)
Get value by specific keyName
Parameters
keyName The key name
value The reference value of DroiDateTime
Returns
true Get value succeeded; Otherwise is false
hasValue()
bool DroiObject::hasValue (const std::string & keyName)
Check whether this keyName exists
Returns
true This keyName is in key-value pair; Otherwise is false
isDirty()
bool DroiObject::isDirty ()
Check whether the object is dirty
Returns
true This object is dirty; Otherwise is false
objectId()
std::string DroiObject::objectId () const inline
Get object identifier
Returns
The string of object identifier
registerCustomClass()
void DroiObject::registerCustomClass (std::string classname, createObject factory) static
Register custom droiobject
Parameters
className The class name of created object.
factory The create function of custom class.
Returns
DroiObject instance
save()
DroiError DroiObject::save () virtual
Save current object to cloud storage
Returns
DroiErr that indicate the error code
References DroiQuery::runQuery().
Referenced by saveAll().
saveAll()
DroiError DroiObject::saveAll (RefVector * items) static
Save all DroiObject objects
References save().
saveInBackground()
void DroiObject::saveInBackground (DroiCallback< DroiError >::onCallback callback)
Save current object to cloud storage in bacgkround thread
Parameters
callback The DroiCallback object
References DroiTaskDispatcher::currentTaskDispatcher(), DroiTaskDispatcher::enqueueTask(), and DroiTaskDispatcher::getTaskDispatcher().
setPermission()
void DroiObject::setPermission (DroiPermission * permission)
Set permission object
Parameters
permission The permission object
References DroiPermission::clone().
Referenced by DroiUser::loginWithAnonymous().
setValue() [1/11]
void DroiObject::setValue (const std::string & keyName, bool value)
Set a key-value pair into DroiObject
Parameters
keyName The key name
value The boolean value
Referenced by DroiUser::signup().
setValue() [2/11]
void DroiObject::setValue (const std::string & keyName, int32_t value)
Set a key-value pair into DroiObject
Parameters
keyName The key name
value The integer value
setValue() [3/11]
void DroiObject::setValue (const std::string & keyName, const std::string & value)
Set a key-value pair into DroiObject
Parameters
keyName The key name
value The integer value
setValue() [4/11]
void DroiObject::setValue (const std::string & keyName, double value)
Set a key-value pair into DroiObject
Parameters
keyName The key name
value The double value
References getValue().
setValue() [5/11]
void DroiObject::setValue (const string & keyName, const cocos2d::Value & value)
Set a key-value pair into DroiObject
Parameters
keyName The key name
value The cocos2d::Value value
setValue() [6/11]
void DroiObject::setValue (const string & keyName, const cocos2d::ValueVector & value)
Set a key-value pair into DroiObject
Parameters
keyName The key name
value The cocos2d::ValueVector value
setValue() [7/11]
void DroiObject::setValue (const string & keyName, const cocos2d::ValueMap & value)
Set a key-value pair into DroiObject
Parameters
keyName The key name
value The cocos2d::ValueMap value
setValue() [8/11]
void DroiObject::setValue (const string & keyName, const RefVector & value)
Set a key-value pair into DroiObject
Parameters
keyName The key name
value The RefVector value
setValue() [9/11]
void DroiObject::setValue (const string & keyName, const RefMap & value)
Set a key-value pair into DroiObject
Parameters
keyName The key name
value The RefMap value
setValue() [10/11]
void DroiObject::setValue (const string & keyName, DroiObject * value)
Set a key-value pair into DroiObject
Parameters
keyName The key name
value The DroiObject value
setValue() [11/11]
void DroiObject::setValue (const string & keyName, DroiDateTime value)
Set a key-value pair into DroiObject
Parameters
keyName The key name
value The DroiDateTime value
toJson()
bool DroiObject::toJson (std::string & result)
Convert this to Json string
The documentation for this class was generated from the following files:
DroiObject.h
DroiObject.cpp