cocos2dSDK: DroiPermission Class Reference
DroiPermission Class Reference
Public Member Functions
DroiPermission ()
~DroiPermission ()
void setUserWritePermission (const char *userId, bool grantPermission)
void setUserReadPermission (const char *userId, bool grantPermission)
void setPublicWritePermission (bool grantPermission)
void setPublicReadPermission (bool grantPermission)
void applyJSONObject (cJSON *json)
cJSON * toJSONObject ()
DroiPermission * clone ()
DroiPermission & operator= (DroiPermission &o)
Static Public Member Functions
static DroiPermission * getDefaultPermission ()
static void setDefaultPermission (DroiPermission *permission)
Constructor & Destructor Documentation
DroiPermission()
DroiPermission::DroiPermission ()
Constructor
~DroiPermission()
DroiPermission::~DroiPermission ()
Destructor
Member Function Documentation
applyJSONObject()
void DroiPermission::applyJSONObject (cJSON * json)
Set group write permission.
Parameters
groupId Group ID
grantPermission true to enable read, false to disable. Set group read permission.
groupId Group ID
grantPermission true to enable read, false to disable. Deserialize from cJSON object.
json JSON object
clone()
DroiPermission * DroiPermission::clone ()
Clone current object
Returns
The clone object
Referenced by DroiObject::setPermission().
getDefaultPermission()
DroiPermission * DroiPermission::getDefaultPermission () static
Get default permission. Will assign to default DroiObject data if not assigned in DroiObject.
Returns
Permission
Referenced by DroiObject::getPermissionWithDefault(), and DroiUser::loginWithAnonymous().
setDefaultPermission()
void DroiPermission::setDefaultPermission (DroiPermission * permission) static
Set default permission. Assign to DroiObject data if not assigned in DroiObject.
Parameters
permission
setPublicReadPermission()
void DroiPermission::setPublicReadPermission (bool grantPermission)
Set public read permission.
Parameters
grantPermission true to enable read, false to disable.
Referenced by DroiUser::loginWithAnonymous().
setPublicWritePermission()
void DroiPermission::setPublicWritePermission (bool grantPermission)
Set public write permission.
Parameters
grantPermission true to enable read, false to disable.
Referenced by DroiUser::loginWithAnonymous().
setUserReadPermission()
void DroiPermission::setUserReadPermission (const char * userId, bool grantPermission)
Set user read permission.
Parameters
userId User ID
grantPermission true to enable read, false to disable.
setUserWritePermission()
void DroiPermission::setUserWritePermission (const char * userId, bool grantPermission)
Set user write permission.
Parameters
userId User ID
grantPermission true to enable read, false to disable.
toJSONObject()
cJSON * DroiPermission::toJSONObject ()
Serialize to JSON format.
Returns
cJSON object
The documentation for this class was generated from the following files:
DroiPermission.h
DroiPermission.cpp