cocos2dSDK: DroiDateTime Class Reference
DroiDateTime Class Reference
Public Member Functions
DroiDateTime ()
DroiDateTime (DroiDateTime &val)
DroiDateTime (const char *iso8601String)
const std::string toISO8601String () const
std::chrono::milliseconds getTime () const
Static Public Member Functions
static std::chrono::milliseconds now ()
static std::string toISO8601String (time_t tm)
static const std::string toISO8601String (std::chrono::milliseconds milisecond)
static bool isValidISO8601String (const char *iso8601String, struct tm *ptm)
static bool isValidISO8601String (const char *iso8601String, std::chrono::milliseconds &pdur)
Constructor & Destructor Documentation
DroiDateTime() [1/3]
DroiDateTime::DroiDateTime ()
Constructor
DroiDateTime() [2/3]
DroiDateTime::DroiDateTime (DroiDateTime & val)
Constructor
Parameters
val DroiDateTime to be copied
DroiDateTime() [3/3]
DroiDateTime::DroiDateTime (const char * iso8601String)
Constructor
Parameters
iso8601String iso8601String to be copied
References isValidISO8601String().
Member Function Documentation
getTime()
std::chrono::milliseconds DroiDateTime::getTime () const inline
Get time in std::chrono::milliseconds
Returns
std::chrono::milliseconds
References isValidISO8601String(), and toISO8601String().
isValidISO8601String() [1/2]
bool DroiDateTime::isValidISO8601String (const char * iso8601String, struct tm * ptm) static
Check iso8601String is valid ISO8601 format or not.
Parameters
iso8601String string to be checked.
ptm tm from converting iso8601String
Returns
true iso8601String is valid ISO8601 format; Otherwise is false
Referenced by DroiDateTime(), getTime(), and DroiUser::isLoggedIn().
isValidISO8601String() [2/2]
bool DroiDateTime::isValidISO8601String (const char * iso8601String, std::chrono::milliseconds & pdur) static
Check iso8601String is valid ISO8601 format or not.
Parameters
iso8601String string to be checked.
pdur std::chrono::milliseconds from converting iso8601String
Returns
true iso8601String is valid ISO8601 format; Otherwise is false
toISO8601String() [1/3]
const std::string DroiDateTime::toISO8601String () const
Get time in ISO8601 string
Returns
string ISO8601 format
Referenced by getTime().
toISO8601String() [2/3]
std::string DroiDateTime::toISO8601String (time_t tm) static
Convert tm to ISO8601 string
Parameters
tm time_t to be converted
Returns
string ISO8601 format
toISO8601String() [3/3]
const std::string DroiDateTime::toISO8601String (std::chrono::milliseconds milisecond) static
Convert milisecond to ISO8601 string
Parameters
milisecond std::chrono::milliseconds to be converted
Returns
string ISO8601 format
The documentation for this class was generated from the following files:
DroiDateTime.h
DroiDateTime.cpp