cocos2dSDK: DroiCore Class Reference
DroiCore Class Reference
#include <DroiCore.h>
Static Public Member Functions
static const std::string getDeviceId ()
static const std::string getInstallationId ()
static const std::string getAppId ()
static void initializeCore (const std::string &applicationId)
Friends
class DroiHttp
class DroiRemoteServiceHelper
Detailed Description
DoireCore provides methods to get Droi AppId, Platform Id and Installation Id information. Developer should use initializeCore to setup Droi Core SDK environment.
Member Function Documentation
getAppId()
const std::string DroiCore::getAppId () static
Get application identifier
Returns
The application identifier
getDeviceId()
const std::string DroiCore::getDeviceId () static
Get device identifier
Returns
The device identifier
Referenced by DroiUser::loginWithAnonymous(), and DroiUser::signup().
getInstallationId()
const std::string DroiCore::getInstallationId () static
Get installation identifier
Returns
The installation identifier
Referenced by DroiUser::login(), DroiUser::loginWithAnonymous(), and DroiUser::signup().
initializeCore()
void DroiCore::initializeCore (const std::string & applicationId) static
Initiate Droi Core SDK
Parameters
applicationId The application identifie
The documentation for this class was generated from the following files:
DroiCore.h
DroiCore.cpp